services:
  db:
    image: mysql:8.0
    container_name: meeting-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meeting
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: meeting-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/meeting?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: on-failure
    command: ["/wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]

volumes:
  db_data:
